name: fieldbioinformatics-medaka
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - bcftools=1.9
  - biopython=1.76
  - bwa=0.7.17=pl5.22.0_2
  - clint=0.5.1=py36_0
  - longshot=0.4.1
  - medaka=0.11.5
  - minimap2=2.17
  - nomkl
  - openblas==0.3.3
  - pandas=0.23.0=py36_1
  - matplotlib
  - pip
  - pysam=0.15.3
  - pytest
  - python=3.6
  - pyvcf=0.6.8
  - samtools=1.9
  - pip:
      - git+https://github.com/artic-network/Porechop.git@v0.3.2pre
      - git+https://github.com/artic-network/fieldbioinformatics.git
