name: artic-ncov2019-illumina
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - python=3
  - biopython=1.74
  - libxcb
  - matplotlib=3.3.3
  - pip
  - pandas=0.23.0=py36_1
  - bwa=0.7.17=pl5.22.0_2
  - samtools=1.10
  - bcftools=1.10
  - trim-galore=0.6.5
  - ivar=1.3
  - muscle=3.8.1551
  - pip:
    - git+https://github.com/connor-lab/aln2type
