name: artic
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - artic=1.1.3
  - pyyaml=5.3.1
  - python>=3.6
  - pip=19.3.1
  - gofasta=0.0.4
  - usher=0.2.0
  - snakemake-minimal=5.13
  - minimap2=2.17
  - nextclade_js=0.14.4
  - pip:
      - pandas == 1.0.1
      - scikit-learn >= 0.23.1
      - git+https://github.com/cov-lineages/pangoLEARN.git
      - git+https://github.com/cov-lineages/pangolin.git
      - git+https://github.com/cov-lineages/constellations.git
      - git+https://github.com/cov-lineages/scorpio.git
      - git+https://github.com/cov-lineages/pango-designation.git