name: artic
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - artic=1.1.3
  - pyyaml=5.3.1
  - python>=3.6
  - pip=19.3.1
  - gofasta=0.0.4
  - usher=0.2.0
  - snakemake-minimal=5.13
  - minimap2=2.17
  - nextclade=1.10.2
  - fastqc=0.11.9
  - multiqc=1.11
  - pip:
      - pandas == 1.0.1
      - scikit-learn >= 0.23.1
  - muscle=3.8
